Repository konbraphat51/AnimatedWordCloud, pull requests merged in 2024-01, with the labels that each got.

#57 Integration of animating
  AnimatedWordCloud/Animator/AllocationCalculator/AllocationCalculator.py
  AnimatedWordCloud/Animator/AllocationCalculator/AnimatetdAllocationCalculator.py
  AnimatedWordCloud/Animator/AllocationCalculator/__init__.py
  AnimatedWordCloud/Animator/Animator.py
  AnimatedWordCloud/Utils/Config.py
  AnimatedWordCloud/__init__.py
  tests/Auto/Animator/Animator_test.py
  tests/Manual/AnimationVisualization.py
Labels: enhancement

#56 Animatedallocation
  AnimatedWordCloud/Animator/AllocationCalculator/AllocationCalculator.py
  AnimatedWordCloud/Animator/AllocationCalculator/AnimatetdAllocationCalculator.py
  AnimatedWordCloud/Animator/AllocationCalculator/__init__.py
  AnimatedWordCloud/Animator/Animator.py
  AnimatedWordCloud/Animator/ImageCreator.py
  AnimatedWordCloud/Utils/Config.py
  AnimatedWordCloud/__init__.py
  tests/Auto/Animator/AllocationCalculator/AnimatedAllocationCalculator_test.py
  tests/Auto/Animator/Animator_test.py
  tests/Manual/AnimationVisualization.py
Labels: enhancement

#62 Fix dup
  AnimatedWordCloud/Animator/ImageCreator.py
  AnimatedWordCloud/Utils/Config.py
  tests/Auto/Animator/ImageCreator_test.py
Labels: bug

#60 Showing timestamp
  AnimatedWordCloud/Animator/AllocationCalculator/AnimatetdAllocationCalculator.py
  AnimatedWordCloud/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationCalculator.py
  AnimatedWordCloud/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationStrategies/MagneticAllocation/MagneticAllocation.py
  AnimatedWordCloud/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationStrategies/RandomAllocation.py
  AnimatedWordCloud/Animator/ImageCreator.py
  AnimatedWordCloud/Utils/Config.py
  AnimatedWordCloud/Utils/Data/AllocationData.py
  tests/Auto/Animator/AllocationCalculator/AnimatedAllocationCalculator_test.py
  tests/Auto/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationCalculator_test.py
  tests/Auto/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationStrategies/MagneticAllocation/MagneticAllocation_test.py
  tests/Auto/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationStrategies/StaticAllocationStrategy_test.py
  tests/Auto/Animator/AnimationIntegrator_test.py
  tests/Auto/Animator/ImageCreator_test.py
  tests/Auto/Utils/AllocationData_test.py
Labels: enhancement

#64 static frame longer
  AnimatedWordCloud/Animator/AnimationIntegrator.py
  AnimatedWordCloud/Animator/Animator.py
  AnimatedWordCloud/Utils/Config.py
  tests/Auto/Animator/AnimationIntegrator_test.py
Labels: enhancement

#58 Documentation
  .gitignore
  CONTRIBUTING.md
  LICENSE
  MANIFEST.in
  README.md
  setup.py
Labels: documentation

#86 movement reluctance
  AnimatedWordCloud/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationCalculator.py
  AnimatedWordCloud/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationStrategies/MagneticAllocation/MagneticAllocation.py
  AnimatedWordCloud/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationStrategies/StaticAllocationStrategy.py
  AnimatedWordCloud/Utils/Config.py
  README.md
  tests/Auto/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationStrategies/MagneticAllocation/MagneticAllocation_test.py
  tests/Auto/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationStrategies/StaticAllocationStrategy_test.py
Labels: enhancement, Refactoring

#89 Fixing static alloaction
  AnimatedWordCloud/Animator/AllocationCalculator/StaticAllocationCalculator/StaticAllocationStrategies/MagneticAllocation/MagnetOuterFrontier.py
Labels: bug

#91 F im speed
  AnimatedWordCloud/Animator/AnimationIntegrator.py
  AnimatedWordCloud/Animator/ImageCreator.py
  tests/Auto/Animator/Animator_test.py
  tests/Auto/Animator/ImageCreator_test.py
Labels: enhancement
